genrule(
	name = "rule_superman",
	srcs = ["scripts/superman"],
	outs = ["superman"],
	cmd = "cat $< > $@"
)


genrule(
	name = "rule_snapsend",
	srcs = ["scripts/snapsend"],
	outs = ["snapsend"],
	cmd = "cat $< > $@"
)


genrule(
	name = "rule_snapreceive",
	srcs = ["scripts/snapreceive"],
	outs = ["snapreceive"],
	cmd = "cat $< > $@"
)



genrule(
	name = "rule_snapsync",
	srcs = ["scripts/snapsync"],
	outs = ["snapsync"],
	cmd = "cat $< > $@"
)

