genrule(
	name = "rule_superman",
	srcs = ["scripts/superman"],
	outs = ["superman"],
	cmd = "cat $< > $@"
)

genrule(
	name = "rule_snapsync",
	srcs = ["scripts/snapsync"],
	outs = ["snapsync"],
	cmd = "cat $< > $@"
)

