genrule(
	name = "rule_dataleech_10min",
	srcs = ["etc/dataleech.10min"],
	outs = ["dataleech"],
	cmd = "cat $< > $@"
)


genrule(
	name = "rule_dataleech_daily",
	srcs = ["etc/dataleech.daily"],
	outs = ["dataleech_daily"],
	cmd = "cat $< > $@"
)
